<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>15</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>622.3039564712813</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>70.94756675296314</KnownMass>
                    <Density>1300.0</Density>
                    <Material>PLA</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>70.94756675296314</CalcMass>
                    <CalcCG>64.64735830249035</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>100.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>5</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>5.0</WallThickness>
                    <ShapeParameter>1.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>57.0</BaseDia>
                    <ShoulderLen>5.0</ShoulderLen>
                    <ShoulderOD>50.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>89.84954989266797</KnownMass>
                    <Density>1300.0</Density>
                    <Material>PLA</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>89.84954989266797</CalcMass>
                    <CalcCG>100.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>200.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>57.0</OD>
                    <ID>53.00000000000001</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>53.00000000000001</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>0.8</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>139.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>139.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>35.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>14.340192366392314</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Altimeter block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>185.0</Xb>
                            <CalcMass>14.340192366392314</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>53.00000000000001</OD>
                            <ID>0.0</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>34.855926535897936</KnownMass>
                            <Density>0.004</Density>
                            <Material>Polyethylene (heavy)</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>34.855926535897936</CalcMass>
                            <CalcCG>87.50000000000001</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>175.00000000000003</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <Dia>1000.0</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>100.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0043</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Elastic cord (flat 6 mm, 1/4 in)</ShroudLineMaterial>
                            <DragCoefficient>0.65</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>336.2446617137153</KnownMass>
                    <Density>1390.0</Density>
                    <Material>PVC</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>336.2446617137153</CalcMass>
                    <CalcCG>350.00000000000006</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>700.0000000000001</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>6</SerialNo>
                    <OD>57.0</OD>
                    <ID>53.00000000000001</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>53.00000000000001</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>91.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Altimeter</Name>
                            <KnownCG>250.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>250.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>120.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <BodyTube>
                            <KnownMass>24.014334244040427</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Electronics bay</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>250.0</Xb>
                            <CalcMass>24.014334244040427</CalcMass>
                            <CalcCG>60.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>120.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>50.0</OD>
                            <ID>48.0</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>48.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>14.294246573833561</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Altimeter block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>245.0</Xb>
                            <CalcMass>14.294246573833561</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>53.00000000000001</OD>
                            <ID>3.0000000000000027</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>60.86898598183306</KnownMass>
                    <Density>1300.0</Density>
                    <Material>PLA</Material>
                    <Name>Tail</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>60.86898598183306</CalcMass>
                    <CalcCG>75.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>150.0</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>10</SerialNo>
                    <OD>57.0</OD>
                    <ID>53.400000000000006</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>53.400000000000006</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>66.16350000000001</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Trapezoidal fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>66.16350000000001</CalcMass>
                            <CalcCG>53.046011292228265</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>11</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>90.0</RootChord>
                            <TipChord>55.0</TipChord>
                            <SemiSpan>65.0</SemiSpan>
                            <SweepDistance>35.00007456059649</SweepDistance>
                            <Thickness>3.6000000000000005</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <LaunchLug>
                            <KnownMass>2.602369690527641</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>100.0</Xb>
                            <CalcMass>2.602369690527641</CalcMass>
                            <CalcCG>15.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>1.0471975511965976</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>30.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>13.600000000000001</OD>
                            <ID>10.0</ID>
                        </LaunchLug>
                        <BodyTube>
                            <KnownMass>40.02389040673405</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Motor bracket</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>40.02389040673405</CalcMass>
                            <CalcCG>100.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>200.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>50.0</OD>
                            <ID>48.0</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>48.0</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>28.99690019263379</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Engine block</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>200.0</Xb>
                            <CalcMass>28.99690019263379</CalcMass>
                            <CalcCG>5.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>10.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>53.400000000000006</OD>
                            <ID>3.4000000000000004</ID>
                            <UsageCode>2</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>6.38932401498112</KnownMass>
                            <Density>1300.0</Density>
                            <Material>PLA</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>6.38932401498112</CalcMass>
                            <CalcCG>2.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>5.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>53.400000000000006</OD>
                            <ID>40.0</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>